### ISSUE TITLE
Upgrade version 

### ISSUE THREAD

**Issue by atbore-phx** [odenio/pgpool-cloudsql#11]
hi @n-oden,
We have recently upgraded our PostgreSQL to V.15 and we also upgraded pgpool internally to be more compliant.
What do you think if we create a PR with these changes ?:
               - 3.18 alpine
               - 1.19 golang
               - telegraf 1.28.1
              - pgpool_exporter 1.2.1
              - latest pkg from alpine => pgpool 4.4.3 (nurikoboshi)

Mainly it concerns the Dockerfile.

All works as charm in our env and pgpool is really stable and it has improved log for debugging.

The only tool we haven't tested is telegraf coz we scapre directly from prometheus so we don't use it.
Let me know if you are interested, 
i'm looking forward to hearing you ;)

**Comment by n-oden** [comment]
Hi @atbore-phx -- this sounds entirely reasonable!

**Comment by atbore-phx** [comment]
Thanks for the reply @n-oden !
I'll post a PR promptly this week.
Best

**Comment by n-oden** [comment]
v1.1.3 is released!
