### ISSUE TITLE
exporting weight's variables

### ISSUE THREAD

**Issue by atbore-phx** [odenio/pgpool-cloudsql#12]
hi @n-oden,
checking the golang templates, i've seen the weight's variables are hard coded:
https://github.com/odenio/pgpool-cloudsql/blob/e44b5d48aa54f4014105f3da2c5d2f2a0ad378cc/conf/pgpool.conf.tmpl#L47
https://github.com/odenio/pgpool-cloudsql/blob/e44b5d48aa54f4014105f3da2c5d2f2a0ad378cc/conf/pgpool.conf.tmpl#L72

What do you think if i produce a PR to create two helm/ENV variables ?
`{{ .PRIMARY_WEIGHT }}` #default 0
`backend_weight{{ $node_id }} = {{ divf $.REPLICAS_WEIGHT $num_replicas }}` # default 1

Main goal:  to customize the loadbalancing ratio using differents weights.

i'm looking forward to hearing you.
Best

**Comment by n-oden** [comment]
So the idea here is that you can spill some portion of the read traffic to the primary by setting a custom `backend_weight0` value?  Sure, seems reasonable.

**Comment by atbore-phx** [comment]
Exactly !

I'll prepare the PR so thanks @n-oden 
Best

**Comment by n-oden** [comment]
merged and released!
